### ISSUE TITLE
댓글 목록 조회 오류

### ISSUE THREAD

**Issue by HwangSeungHyeon** [96KimBoseong/velog#14]
## 발생한 에러
게시글 id 와는 상관 없이 모든 댓글을 출력하게 됨

## 해결 방법
1. postId가 service 레이어로 전달되지 않아서 발생된 문제이므로 이를 수정한다.

**Comment by 96KimBoseong** [comment]
확인했습니다

**Comment by kr01126kr** [comment]
check

**Comment by justhyeonseok** [comment]
gooooood
